--insert into Student (FirstName, LastName, SlackHandle, CohortId) VALUES ('Noah', 'Barfield', 'NoahBarfield', 1);
--insert into Student (FirstName, LastName, SlackHandle, CohortId) VALUES ('Bobby', 'Brady', 'BobbyBrady', 1);
--insert into Student (FirstName, LastName, SlackHandle, CohortId) VALUES ('Matt', 'Ross', 'MattRoss', 1);
--insert into Student (FirstName, LastName, SlackHandle, CohortId) VALUES ('Bito', 'Mann', 'BitoMann', 3);
--insert into Student (FirstName, LastName, SlackHandle, CohortId) VALUES ('James', 'McClarty', 'JamesMcClarty', 2);
--insert into Student (FirstName, LastName, SlackHandle, CohortId) VALUES ('Will', 'Wilkinson', 'WillWilkinson', 1);